import type { StoryIconName } from "../primitives/StoryIcon.tsx";

export type NarrativeRole = "hook" | "intro" | "chapter" | "question" | "quote" | "fact" | "evidence" | "comparison" | "timeline" | "context" | "explanation" | "transition" | "conclusion" | "outro";
export type InformationShape = "headline" | "long-text" | "single-fact" | "single-statistic" | "categorical-series" | "time-series" | "part-to-whole" | "ordered-list" | "two-sided-comparison" | "before-after" | "chronology" | "document" | "person-profile" | "location-profile" | "route" | "process" | "cause-effect" | "single-image" | "image-sequence" | "image-comparison" | "image-with-callout" | "image-mosaic";
export type ComponentTone = "authoritative" | "investigative" | "urgent" | "reflective" | "archival" | "human" | "analytical" | "dramatic" | "neutral";
export type MediaMode = "none" | "optional-image" | "required-image" | "multiple-images" | "two-images";
export type InputKind = "string" | "number" | "boolean" | "array" | "object" | "icon" | "image";

export interface ComponentInputField {
  name: string;
  kind: InputKind;
  required: boolean;
  description: string;
  maxItems?: number;
  maxCharacters?: number;
}

export interface ComponentCapability {
  slug: string;
  name: string;
  category: string;
  purpose: string;
  narrativeRoles: NarrativeRole[];
  informationShapes: InformationShape[];
  tones: ComponentTone[];
  media: { mode: MediaMode; min: number; max: number; treatments: readonly string[] };
  icons: { accepts: boolean; recommended: StoryIconName[] };
  inputs: ComponentInputField[];
  bestFor: string[];
  avoidWhen: string[];
  selectionHint: string;
  durationFrames: { min: number; ideal: number; max: number };
  textBudget: { headline?: number; body?: number; items?: number };
}

const f = (name: string, kind: InputKind, required: boolean, description: string, limits: Pick<ComponentInputField, "maxItems" | "maxCharacters"> = {}): ComponentInputField => ({ name, kind, required, description, ...limits });
const c = (capability: ComponentCapability): ComponentCapability => capability;
const noMedia = { mode: "none", min: 0, max: 0, treatments: [] } as const;
const optionalImage = { mode: "optional-image", min: 0, max: 1, treatments: ["clean", "documentary", "archive", "monochrome"] } as const;
const oneImage = { mode: "required-image", min: 1, max: 1, treatments: ["clean", "documentary", "archive", "monochrome"] } as const;
const baseDuration = { min: 90, ideal: 150, max: 210 };

export const componentCapabilities: ComponentCapability[] = [
  c({ slug: "title-card", name: "Title Card", category: "Intro & Outro", purpose: "Open a documentary or major section with a cinematic title.", narrativeRoles: ["intro", "hook"], informationShapes: ["headline"], tones: ["dramatic", "authoritative"], media: noMedia, icons: { accepts: false, recommended: [] }, inputs: [f("title", "string", true, "Primary title", { maxCharacters: 70 }), f("subtitle", "string", true, "Short subtitle", { maxCharacters: 80 })], bestFor: ["episode openings", "major section openings"], avoidWhen: ["the message is a question", "a factual source must be shown"], selectionHint: "Choose for a formal opening, not an in-story fact beat.", durationFrames: { min: 90, ideal: 150, max: 180 }, textBudget: { headline: 70, body: 80 } }),
  c({ slug: "end-card", name: "End Card", category: "Intro & Outro", purpose: "Close the video with a final message and action.", narrativeRoles: ["outro", "conclusion"], informationShapes: ["headline"], tones: ["authoritative", "reflective"], media: noMedia, icons: { accepts: false, recommended: [] }, inputs: [f("text", "string", false, "Closing line", { maxCharacters: 60 }), f("ctaText", "string", false, "Action label", { maxCharacters: 30 }), f("footerText", "string", false, "Channel or series line", { maxCharacters: 50 })], bestFor: ["video endings", "calls to action"], avoidWhen: ["new evidence is still being introduced"], selectionHint: "Use only at the end of the complete story.", durationFrames: { min: 90, ideal: 120, max: 180 }, textBudget: { headline: 60, body: 50 } }),
  c({ slug: "bar-chart", name: "Editorial Bar Chart", category: "Charts & Data", purpose: "Compare a small set of discrete values with immediate ranking.", narrativeRoles: ["fact", "evidence", "comparison"], informationShapes: ["categorical-series"], tones: ["analytical", "authoritative"], media: noMedia, icons: { accepts: true, recommended: ["trend", "scale"] }, inputs: [f("title", "string", true, "Chart headline", { maxCharacters: 70 }), f("bars", "array", true, "Three to six labeled values", { maxItems: 6 }), f("maxValue", "number", true, "Scale maximum"), f("yAxisLabel", "string", false, "Unit label", { maxCharacters: 30 })], bestFor: ["category ranking", "discrete year comparisons"], avoidWhen: ["there is only one value", "there are more than six values", "the data is continuous"], selectionHint: "Choose when relative bar length is the story.", durationFrames: baseDuration, textBudget: { headline: 70, items: 6 } }),
  c({ slug: "line-chart", name: "Editorial Trend Line", category: "Charts & Data", purpose: "Show one continuous trend and emphasize its direction or turning point.", narrativeRoles: ["fact", "evidence"], informationShapes: ["time-series"], tones: ["analytical", "investigative"], media: noMedia, icons: { accepts: true, recommended: ["trend", "time"] }, inputs: [f("title", "string", true, "Trend headline", { maxCharacters: 70 }), f("points", "array", true, "Three to eight ordered points", { maxItems: 8 }), f("maxValue", "number", true, "Scale maximum"), f("yAxisLabel", "string", false, "Unit label", { maxCharacters: 30 })], bestFor: ["changes over time", "turning points"], avoidWhen: ["the categories are unordered", "exact comparison between many series is needed"], selectionHint: "Choose when slope and direction matter more than individual categories.", durationFrames: baseDuration, textBudget: { headline: 70, items: 8 } }),
  c({ slug: "pie-chart", name: "Editorial Share Wheel", category: "Charts & Data", purpose: "Show a simple part-to-whole composition with one dominant segment.", narrativeRoles: ["fact", "evidence"], informationShapes: ["part-to-whole"], tones: ["analytical", "neutral"], media: noMedia, icons: { accepts: true, recommended: ["layers"] }, inputs: [f("title", "string", true, "Composition headline", { maxCharacters: 70 }), f("segments", "array", true, "Two to four shares", { maxItems: 4 })], bestFor: ["simple composition", "dominant share"], avoidWhen: ["precise comparison matters", "there are more than four segments", "values do not form a whole"], selectionHint: "Use sparingly; prefer bars unless part-to-whole is the key message.", durationFrames: baseDuration, textBudget: { headline: 70, items: 4 } }),
  c({ slug: "circular-progress", name: "Editorial Gauge", category: "Charts & Data", purpose: "Show one percentage or completion value as a physical gauge.", narrativeRoles: ["fact", "evidence"], informationShapes: ["single-statistic"], tones: ["analytical", "urgent"], media: noMedia, icons: { accepts: true, recommended: ["trend", "time", "shield"] }, inputs: [f("title", "string", true, "Gauge headline", { maxCharacters: 70 }), f("percentage", "number", true, "Percentage value"), f("label", "string", true, "Meaning of the value", { maxCharacters: 90 }), f("sublabel", "string", false, "Unit or qualifier", { maxCharacters: 30 })], bestFor: ["completion", "one percentage", "risk score"], avoidWhen: ["multiple values must be compared"], selectionHint: "Choose for exactly one normalized value between zero and one hundred.", durationFrames: baseDuration, textBudget: { headline: 70, body: 90 } }),
  c({ slug: "animated-list", name: "Editorial List", category: "Content Animation", purpose: "Reveal a concise ordered or grouped list with visual progression.", narrativeRoles: ["explanation", "fact"], informationShapes: ["ordered-list"], tones: ["authoritative", "analytical"], media: noMedia, icons: { accepts: true, recommended: ["workflow", "check", "document"] }, inputs: [f("title", "string", true, "List headline", { maxCharacters: 70 }), f("items", "array", true, "Two to four items", { maxItems: 4 })], bestFor: ["principles", "short checklists", "ranked points"], avoidWhen: ["items have causal dependencies", "more than four items are required"], selectionHint: "Choose when the items are peers; use Process Steps when order causes progression.", durationFrames: baseDuration, textBudget: { headline: 70, items: 4 } }),

  c({ slug: "hook-headline", name: "Hook Headline", category: "Narrative", purpose: "Deliver the opening premise with maximum typographic impact.", narrativeRoles: ["hook", "intro"], informationShapes: ["headline"], tones: ["dramatic", "urgent", "investigative"], media: optionalImage, icons: { accepts: true, recommended: ["zap", "archive", "newspaper"] }, inputs: [f("kicker", "string", true, "Short framing label", { maxCharacters: 35 }), f("headline", "string", true, "Primary hook", { maxCharacters: 55 }), f("emphasis", "string", false, "Emphasized phrase", { maxCharacters: 35 }), f("context", "string", false, "One sentence of context", { maxCharacters: 130 }), f("imageUrl", "image", false, "Optional hero image"), f("icon", "icon", false, "Story-specific icon")], bestFor: ["first two seconds", "chapter cold opens", "high-stakes premise"], avoidWhen: ["the copy exceeds two short sentences", "a source citation is the focal point"], selectionHint: "Use once near the opening when the premise itself is the visual.", durationFrames: { min: 90, ideal: 135, max: 180 }, textBudget: { headline: 55, body: 130 } }),
  c({ slug: "chapter-card", name: "Chapter Card", category: "Narrative", purpose: "Mark a major structural turn with a numbered editorial plate.", narrativeRoles: ["chapter", "transition"], informationShapes: ["headline"], tones: ["authoritative", "dramatic"], media: optionalImage, icons: { accepts: true, recommended: ["book", "flag", "archive"] }, inputs: [f("chapter", "string", true, "Chapter label", { maxCharacters: 35 }), f("number", "number", true, "Chapter number"), f("title", "string", true, "Chapter title", { maxCharacters: 65 }), f("summary", "string", false, "One-sentence preview", { maxCharacters: 130 }), f("imageUrl", "image", false, "Optional chapter image")], bestFor: ["major story turns", "multi-part documentaries"], avoidWhen: ["the beat is not a real structural transition"], selectionHint: "Use between major acts, not between every scene.", durationFrames: { min: 90, ideal: 135, max: 180 }, textBudget: { headline: 65, body: 130 } }),
  c({ slug: "question-card", name: "Question Card", category: "Narrative", purpose: "Frame the central uncertainty the documentary will investigate.", narrativeRoles: ["question", "hook"], informationShapes: ["headline"], tones: ["investigative", "reflective"], media: noMedia, icons: { accepts: true, recommended: ["question", "search"] }, inputs: [f("question", "string", true, "Central question", { maxCharacters: 120 }), f("topic", "string", false, "Framing label", { maxCharacters: 35 }), f("prompt", "string", false, "Viewing prompt", { maxCharacters: 100 })], bestFor: ["central mystery", "ethical dilemma", "investigative pivot"], avoidWhen: ["the answer is already being stated"], selectionHint: "Choose when uncertainty is the narrative engine.", durationFrames: { min: 100, ideal: 135, max: 180 }, textBudget: { headline: 120, body: 100 } }),
  c({ slug: "quote-card", name: "Quote Card", category: "Narrative", purpose: "Present an attributed statement with editorial authority.", narrativeRoles: ["quote", "evidence"], informationShapes: ["long-text"], tones: ["human", "reflective", "archival"], media: optionalImage, icons: { accepts: true, recommended: ["quote", "user"] }, inputs: [f("quote", "string", true, "Quoted statement", { maxCharacters: 220 }), f("speaker", "string", true, "Speaker name", { maxCharacters: 50 }), f("role", "string", false, "Speaker context", { maxCharacters: 70 }), f("year", "string", false, "Date label", { maxCharacters: 20 }), f("imageUrl", "image", false, "Optional speaker image")], bestFor: ["witness testimony", "expert statements", "historical quotations"], avoidWhen: ["the text is paraphrased", "attribution is unavailable"], selectionHint: "Choose only for verbatim attributed language.", durationFrames: { min: 120, ideal: 150, max: 210 }, textBudget: { body: 220 } }),
  c({ slug: "conclusion-card", name: "Conclusion Card", category: "Narrative", purpose: "Resolve the argument with one conclusion and one takeaway.", narrativeRoles: ["conclusion", "outro"], informationShapes: ["long-text"], tones: ["authoritative", "reflective"], media: noMedia, icons: { accepts: true, recommended: ["flag", "check", "question"] }, inputs: [f("conclusion", "string", true, "Main conclusion", { maxCharacters: 100 }), f("takeaway", "string", true, "Final implication", { maxCharacters: 190 }), f("closingQuestion", "string", false, "Optional audience question", { maxCharacters: 90 })], bestFor: ["argument resolution", "chapter ending", "final implication"], avoidWhen: ["new evidence still needs explanation"], selectionHint: "Use after the evidence, when the viewer should leave with one sentence.", durationFrames: { min: 120, ideal: 150, max: 210 }, textBudget: { headline: 100, body: 190 } }),

  c({ slug: "key-fact", name: "Key Fact", category: "Facts & Data", purpose: "Reveal one surprising verified fact as a visual interruption.", narrativeRoles: ["fact", "evidence"], informationShapes: ["single-fact"], tones: ["urgent", "authoritative"], media: noMedia, icons: { accepts: true, recommended: ["alert", "fingerprint", "document"] }, inputs: [f("fact", "string", true, "Verified fact", { maxCharacters: 150 }), f("detail", "string", false, "Context sentence", { maxCharacters: 150 }), f("source", "string", false, "Source label", { maxCharacters: 70 }), f("icon", "icon", false, "Semantic icon")], bestFor: ["surprising fact", "critical correction", "hard narrative turn"], avoidWhen: ["multiple values need comparison", "the statement is opinion"], selectionHint: "Choose for one sentence the viewer must remember.", durationFrames: { min: 90, ideal: 135, max: 180 }, textBudget: { headline: 150, body: 150 } }),
  c({ slug: "statistic-spotlight", name: "Statistic Spotlight", category: "Facts & Data", purpose: "Give one number physical scale and contextual meaning.", narrativeRoles: ["fact", "evidence"], informationShapes: ["single-statistic"], tones: ["analytical", "dramatic"], media: noMedia, icons: { accepts: true, recommended: ["trend", "user", "globe"] }, inputs: [f("label", "string", true, "Metric label", { maxCharacters: 45 }), f("value", "number", true, "Numeric value"), f("context", "string", true, "Meaning of the number", { maxCharacters: 150 }), f("prefix", "string", false, "Value prefix"), f("suffix", "string", false, "Value suffix"), f("scaleMax", "number", false, "Visual scale maximum")], bestFor: ["one impactful metric", "population scale", "cost or percentage"], avoidWhen: ["several metrics matter equally"], selectionHint: "Choose when the number itself is the beat.", durationFrames: { min: 110, ideal: 150, max: 190 }, textBudget: { headline: 45, body: 150 } }),
  c({ slug: "myth-fact", name: "Claim Audit", category: "Facts & Data", purpose: "Replace one false claim with one evidence-backed correction.", narrativeRoles: ["fact", "evidence", "comparison"], informationShapes: ["two-sided-comparison"], tones: ["investigative", "authoritative"], media: noMedia, icons: { accepts: true, recommended: ["scale", "x", "check"] }, inputs: [f("myth", "string", true, "Incorrect claim", { maxCharacters: 140 }), f("fact", "string", true, "Correction", { maxCharacters: 170 }), f("source", "string", false, "Evidence source", { maxCharacters: 70 })], bestFor: ["debunking", "fact checks", "record correction"], avoidWhen: ["both sides are legitimate perspectives"], selectionHint: "Use only when one claim is demonstrably false.", durationFrames: { min: 120, ideal: 150, max: 200 }, textBudget: { body: 170 } }),
  c({ slug: "comparison-split", name: "Comparison Split", category: "Facts & Data", purpose: "Contrast exactly two values, accounts, or systems.", narrativeRoles: ["comparison", "evidence"], informationShapes: ["two-sided-comparison"], tones: ["analytical", "authoritative"], media: noMedia, icons: { accepts: true, recommended: ["scale", "document", "archive"] }, inputs: [f("title", "string", true, "Comparison frame", { maxCharacters: 70 }), f("left", "object", true, "First side"), f("right", "object", true, "Second side"), f("verdict", "string", false, "Difference summary", { maxCharacters: 60 })], bestFor: ["official vs archive", "two policy options", "paired values"], avoidWhen: ["there are more than two items", "a temporal before-after relationship is primary"], selectionHint: "Choose for two peer alternatives; use Before & After for time-based change.", durationFrames: baseDuration, textBudget: { headline: 70, items: 2 } }),
  c({ slug: "before-after", name: "Before & After", category: "Facts & Data", purpose: "Show one measurable state changing into another over time.", narrativeRoles: ["comparison", "evidence"], informationShapes: ["before-after"], tones: ["analytical", "dramatic"], media: noMedia, icons: { accepts: false, recommended: [] }, inputs: [f("title", "string", true, "Transformation headline", { maxCharacters: 70 }), f("before", "object", true, "Earlier state"), f("after", "object", true, "Later state"), f("change", "string", false, "Change summary", { maxCharacters: 60 })], bestFor: ["historical change", "policy impact", "measurable transformation"], avoidWhen: ["the two states are not temporal"], selectionHint: "Choose when movement through time is essential to the comparison.", durationFrames: baseDuration, textBudget: { headline: 70, items: 2 } }),

  c({ slug: "evidence-card", name: "Evidence File", category: "Evidence", purpose: "Present one corroborated finding and its confidence level.", narrativeRoles: ["evidence", "fact"], informationShapes: ["single-fact"], tones: ["investigative", "authoritative"], media: optionalImage, icons: { accepts: true, recommended: ["fingerprint", "shield", "scan"] }, inputs: [f("title", "string", true, "Finding headline", { maxCharacters: 85 }), f("finding", "string", true, "Evidence statement", { maxCharacters: 220 }), f("confidence", "string", false, "High, medium, or low confidence"), f("source", "string", false, "Evidence source", { maxCharacters: 70 }), f("imageUrl", "image", false, "Optional exhibit image")], bestFor: ["verified finding", "forensic result", "research conclusion"], avoidWhen: ["the source itself needs to be read", "the statement is unattributed opinion"], selectionHint: "Choose when confidence and corroboration are part of the story.", durationFrames: baseDuration, textBudget: { headline: 85, body: 220 } }),
  c({ slug: "source-citation", name: "Source Citation", category: "Evidence", purpose: "Put a publication or archival source visibly on record.", narrativeRoles: ["evidence"], informationShapes: ["document", "long-text"], tones: ["archival", "authoritative"], media: noMedia, icons: { accepts: true, recommended: ["link", "book", "archive"] }, inputs: [f("publisher", "string", true, "Publisher or archive", { maxCharacters: 60 }), f("title", "string", true, "Source title", { maxCharacters: 110 }), f("date", "string", false, "Publication date", { maxCharacters: 30 }), f("excerpt", "string", false, "Short quotation", { maxCharacters: 180 }), f("urlLabel", "string", false, "Readable source locator", { maxCharacters: 80 })], bestFor: ["source transparency", "archival attribution", "citation beat"], avoidWhen: ["the source is not important enough to interrupt the story"], selectionHint: "Choose when viewers should see exactly where a claim came from.", durationFrames: baseDuration, textBudget: { headline: 110, body: 180 } }),
  c({ slug: "document-reveal", name: "Document Reveal", category: "Evidence", purpose: "Reveal the relevant language inside an archival or official document.", narrativeRoles: ["evidence", "context"], informationShapes: ["document"], tones: ["archival", "investigative"], media: noMedia, icons: { accepts: true, recommended: ["document", "archive", "newspaper"] }, inputs: [f("title", "string", true, "Document heading", { maxCharacters: 70 }), f("lines", "array", true, "Up to five document lines", { maxItems: 5 }), f("documentType", "string", false, "Document class", { maxCharacters: 45 }), f("date", "string", false, "Document date", { maxCharacters: 30 }), f("highlightIndex", "number", false, "Line to emphasize"), f("stamp", "string", false, "Status stamp", { maxCharacters: 20 })], bestFor: ["memos", "letters", "declassified records"], avoidWhen: ["the document requires more than five readable lines", "only a source citation is needed"], selectionHint: "Choose when the wording inside the document is the evidence.", durationFrames: { min: 140, ideal: 180, max: 240 }, textBudget: { headline: 70, items: 5 } }),
  c({ slug: "timeline", name: "Documentary Timeline", category: "Evidence", purpose: "Compress two to four dated events into a causal chronology.", narrativeRoles: ["timeline", "context", "evidence"], informationShapes: ["chronology"], tones: ["authoritative", "investigative"], media: noMedia, icons: { accepts: true, recommended: ["calendar", "flag", "time"] }, inputs: [f("title", "string", true, "Chronology headline", { maxCharacters: 70 }), f("events", "array", true, "Two to four events", { maxItems: 4 })], bestFor: ["historical sequence", "crisis progression", "policy chronology"], avoidWhen: ["there are more than four events", "dates are uncertain or unordered"], selectionHint: "Choose when sequence explains causality.", durationFrames: { min: 150, ideal: 180, max: 240 }, textBudget: { headline: 70, items: 4 } }),
  c({ slug: "event-countdown", name: "Event Countdown", category: "Evidence", purpose: "Make limited time or an approaching deadline feel physical.", narrativeRoles: ["evidence", "transition"], informationShapes: ["single-statistic"], tones: ["urgent", "dramatic"], media: noMedia, icons: { accepts: true, recommended: ["time", "alert"] }, inputs: [f("count", "number", true, "Remaining amount"), f("unit", "string", true, "Time unit", { maxCharacters: 15 }), f("event", "string", true, "Approaching event", { maxCharacters: 90 }), f("detail", "string", false, "Human consequence", { maxCharacters: 120 })], bestFor: ["deadlines", "closing borders", "days until impact"], avoidWhen: ["the value is not time-related"], selectionHint: "Choose when urgency comes from a finite clock.", durationFrames: { min: 90, ideal: 135, max: 180 }, textBudget: { headline: 90, body: 120 } }),

  c({ slug: "person-profile", name: "Person Profile", category: "People & Places", purpose: "Introduce a key person through portrait, role, and three facts.", narrativeRoles: ["context", "evidence"], informationShapes: ["person-profile"], tones: ["human", "authoritative", "archival"], media: optionalImage, icons: { accepts: true, recommended: ["user", "camera", "document"] }, inputs: [f("name", "string", true, "Person name", { maxCharacters: 45 }), f("role", "string", true, "Narrative role", { maxCharacters: 45 }), f("description", "string", true, "Why this person matters", { maxCharacters: 180 }), f("facts", "array", false, "Up to three supporting facts", { maxItems: 3 }), f("imageUrl", "image", false, "Portrait image")], bestFor: ["key figure introduction", "witness profile", "expert context"], avoidWhen: ["the person is only mentioned once", "no meaningful role can be stated"], selectionHint: "Choose when understanding the person changes how the story is read.", durationFrames: { min: 135, ideal: 165, max: 220 }, textBudget: { headline: 45, body: 180, items: 3 } }),
  c({ slug: "location-card", name: "Location Dossier", category: "People & Places", purpose: "Establish a place through an image, significance, coordinates, and compact facts.", narrativeRoles: ["context", "transition"], informationShapes: ["location-profile"], tones: ["human", "archival", "authoritative"], media: optionalImage, icons: { accepts: true, recommended: ["compass", "location", "globe"] }, inputs: [f("place", "string", true, "Place name", { maxCharacters: 45 }), f("significance", "string", true, "Why it matters", { maxCharacters: 170 }), f("facts", "array", false, "Up to three place facts", { maxItems: 3 }), f("coordinates", "string", false, "Coordinate label", { maxCharacters: 45 }), f("imageUrl", "image", false, "Location image")], bestFor: ["scene setting", "historical site", "geographic context"], avoidWhen: ["movement between places is the story"], selectionHint: "Choose to establish one place; use Map Route for travel between places.", durationFrames: baseDuration, textBudget: { headline: 45, body: 170, items: 3 } }),
  c({ slug: "map-route", name: "Map Route", category: "People & Places", purpose: "Visualize movement from one named place to another.", narrativeRoles: ["context", "explanation", "transition"], informationShapes: ["route"], tones: ["investigative", "analytical"], media: noMedia, icons: { accepts: true, recommended: ["route", "location", "flag"] }, inputs: [f("title", "string", true, "Journey label", { maxCharacters: 65 }), f("origin", "string", true, "Start place", { maxCharacters: 35 }), f("destination", "string", true, "End place", { maxCharacters: 35 }), f("distance", "string", false, "Distance label", { maxCharacters: 25 }), f("note", "string", false, "Journey consequence", { maxCharacters: 130 })], bestFor: ["evacuation", "migration", "expedition", "supply route"], avoidWhen: ["only one place matters", "accurate cartography is required"], selectionHint: "Choose for narrative movement, not geographic precision.", durationFrames: { min: 135, ideal: 165, max: 210 }, textBudget: { headline: 65, body: 130 } }),
  c({ slug: "process-steps", name: "Process Steps", category: "Explainers", purpose: "Explain a causal sequence of two to four operational stages.", narrativeRoles: ["explanation"], informationShapes: ["process"], tones: ["analytical", "authoritative"], media: noMedia, icons: { accepts: true, recommended: ["workflow", "search", "shield", "zap"] }, inputs: [f("title", "string", true, "Process headline", { maxCharacters: 70 }), f("steps", "array", true, "Two to four sequential stages", { maxItems: 4 })], bestFor: ["how an operation worked", "investigative method", "system sequence"], avoidWhen: ["items are independent", "more than four stages are necessary"], selectionHint: "Choose when each stage leads into the next.", durationFrames: { min: 135, ideal: 165, max: 220 }, textBudget: { headline: 70, items: 4 } }),
  c({ slug: "cause-effect", name: "Cause & Effect", category: "Explainers", purpose: "Connect one initiating cause to one consequential effect.", narrativeRoles: ["explanation", "evidence"], informationShapes: ["cause-effect"], tones: ["analytical", "dramatic"], media: noMedia, icons: { accepts: true, recommended: ["alert", "trend", "zap"] }, inputs: [f("title", "string", true, "Causal frame", { maxCharacters: 70 }), f("cause", "object", true, "Initiating cause"), f("effect", "object", true, "Resulting effect"), f("connector", "string", false, "Causal summary", { maxCharacters: 70 })], bestFor: ["one clear causal link", "policy consequence", "chain reaction"], avoidWhen: ["there are multiple causes or effects", "causality is uncertain"], selectionHint: "Choose only when the causal claim is supported and singular.", durationFrames: baseDuration, textBudget: { headline: 70, items: 2 } }),

  c({ slug: "hero-image-story", name: "Hero Image Story", category: "Image & Media", purpose: "Lead a beat with one cinematic image and a strong editorial headline.", narrativeRoles: ["hook", "intro", "context"], informationShapes: ["single-image", "headline"], tones: ["dramatic", "human", "archival"], media: oneImage, icons: { accepts: true, recommended: ["camera", "archive"] }, inputs: [f("imageUrl", "image", true, "Hero image"), f("title", "string", true, "Image-led headline", { maxCharacters: 75 }), f("subtitle", "string", false, "One sentence of context", { maxCharacters: 140 }), f("credit", "string", false, "Image credit", { maxCharacters: 70 })], bestFor: ["scene opener", "powerful establishing image", "visual thesis"], avoidWhen: ["the image is low resolution", "several images matter equally"], selectionHint: "Choose when one image carries most of the emotional information.", durationFrames: { min: 120, ideal: 165, max: 220 }, textBudget: { headline: 75, body: 140 } }),
  c({ slug: "archival-photo", name: "Archival Photo", category: "Image & Media", purpose: "Present one historical photograph as a physical archival object.", narrativeRoles: ["evidence", "context"], informationShapes: ["single-image"], tones: ["archival", "reflective"], media: oneImage, icons: { accepts: false, recommended: [] }, inputs: [f("imageUrl", "image", true, "Historical photograph"), f("title", "string", true, "Photo title", { maxCharacters: 80 }), f("caption", "string", true, "What the image shows", { maxCharacters: 160 }), f("date", "string", false, "Photo date", { maxCharacters: 30 }), f("location", "string", false, "Photo location", { maxCharacters: 45 })], bestFor: ["historical photo", "archive evidence", "memory beat"], avoidWhen: ["the image is modern UI or a clean infographic"], selectionHint: "Choose for a single photograph whose age and provenance matter.", durationFrames: { min: 140, ideal: 180, max: 240 }, textBudget: { headline: 80, body: 160 } }),
  c({ slug: "photo-stack", name: "Photo Stack", category: "Image & Media", purpose: "Reveal two or three related photographs as a tactile collection.", narrativeRoles: ["context", "evidence", "transition"], informationShapes: ["image-sequence"], tones: ["human", "archival", "reflective"], media: { mode: "multiple-images", min: 2, max: 3, treatments: ["documentary", "archive", "monochrome"] }, icons: { accepts: false, recommended: [] }, inputs: [f("title", "string", true, "Collection title", { maxCharacters: 70 }), f("images", "array", true, "Two or three images", { maxItems: 3 }), f("note", "string", false, "Collection context", { maxCharacters: 120 })], bestFor: ["visual montage", "family archive", "related evidence photos"], avoidWhen: ["one image should dominate", "images are unrelated"], selectionHint: "Choose when the relationship between several photos is the story.", durationFrames: { min: 140, ideal: 180, max: 240 }, textBudget: { headline: 70, body: 120, items: 3 } }),
  c({ slug: "image-comparison", name: "Image Comparison", category: "Image & Media", purpose: "Compare two images through an animated visual wipe.", narrativeRoles: ["comparison", "evidence"], informationShapes: ["image-comparison", "before-after"], tones: ["analytical", "dramatic"], media: { mode: "two-images", min: 2, max: 2, treatments: ["clean", "documentary", "monochrome"] }, icons: { accepts: false, recommended: [] }, inputs: [f("title", "string", true, "Comparison label", { maxCharacters: 70 }), f("before", "object", true, "First image and label"), f("after", "object", true, "Second image and label"), f("note", "string", false, "Difference summary", { maxCharacters: 90 })], bestFor: ["visual transformation", "same place across time", "evidence comparison"], avoidWhen: ["the images have different framing", "the difference is primarily numeric"], selectionHint: "Choose when viewers can understand the difference by looking.", durationFrames: { min: 135, ideal: 180, max: 240 }, textBudget: { headline: 70, body: 90 } }),
  c({ slug: "image-quote", name: "Image Quote", category: "Image & Media", purpose: "Pair an emotional image with a short attributed quotation.", narrativeRoles: ["quote", "evidence"], informationShapes: ["single-image", "long-text"], tones: ["human", "reflective", "dramatic"], media: oneImage, icons: { accepts: false, recommended: [] }, inputs: [f("imageUrl", "image", true, "Background image"), f("quote", "string", true, "Attributed quotation", { maxCharacters: 180 }), f("speaker", "string", true, "Speaker name", { maxCharacters: 50 }), f("context", "string", false, "Speaker context", { maxCharacters: 70 })], bestFor: ["witness testimony", "emotional quotation", "character-led beat"], avoidWhen: ["the image does not relate to the speaker", "the quote is long"], selectionHint: "Choose when image and testimony reinforce the same emotion.", durationFrames: { min: 140, ideal: 180, max: 230 }, textBudget: { body: 180 } }),
  c({ slug: "evidence-zoom", name: "Evidence Zoom", category: "Image & Media", purpose: "Direct attention to one meaningful detail inside an image.", narrativeRoles: ["evidence", "explanation"], informationShapes: ["image-with-callout"], tones: ["investigative", "analytical"], media: oneImage, icons: { accepts: false, recommended: [] }, inputs: [f("imageUrl", "image", true, "Evidence image"), f("callout", "string", true, "Meaning of the target detail", { maxCharacters: 100 }), f("targetX", "number", true, "Horizontal target percentage"), f("targetY", "number", true, "Vertical target percentage"), f("source", "string", false, "Image source", { maxCharacters: 70 })], bestFor: ["forensic detail", "photo anomaly", "map or document detail"], avoidWhen: ["several details need separate callouts", "the target is too small to survive mobile viewing"], selectionHint: "Choose when one visible detail proves or explains the point.", durationFrames: { min: 135, ideal: 180, max: 230 }, textBudget: { body: 100 } }),
  c({ slug: "image-mosaic", name: "Image Mosaic", category: "Image & Media", purpose: "Show three complementary images in a deliberate editorial composition.", narrativeRoles: ["context", "transition", "evidence"], informationShapes: ["image-mosaic"], tones: ["human", "dramatic", "archival"], media: { mode: "multiple-images", min: 2, max: 3, treatments: ["clean", "documentary", "archive"] }, icons: { accepts: false, recommended: [] }, inputs: [f("title", "string", true, "Mosaic headline", { maxCharacters: 70 }), f("images", "array", true, "Two or three complementary images", { maxItems: 3 }), f("credit", "string", false, "Image credit", { maxCharacters: 70 })], bestFor: ["place montage", "visual evidence set", "scene-setting collage"], avoidWhen: ["one image deserves focus", "images have conflicting visual styles"], selectionHint: "Choose for a compact visual world, not a chronological sequence.", durationFrames: { min: 140, ideal: 180, max: 240 }, textBudget: { headline: 70, items: 3 } }),
  c({ slug: "captioned-image", name: "Captioned Image", category: "Image & Media", purpose: "Explain what viewers are seeing without overpowering the image.", narrativeRoles: ["context", "evidence"], informationShapes: ["single-image"], tones: ["authoritative", "human", "neutral"], media: oneImage, icons: { accepts: true, recommended: ["camera", "location", "document"] }, inputs: [f("imageUrl", "image", true, "Primary image"), f("caption", "string", true, "Essential visual explanation", { maxCharacters: 150 }), f("detail", "string", false, "Secondary context", { maxCharacters: 110 }), f("credit", "string", false, "Image credit", { maxCharacters: 70 }), f("icon", "icon", false, "Caption context icon")], bestFor: ["establishing shot", "historical image explanation", "scene context"], avoidWhen: ["the image needs a callout", "the caption is longer than two sentences"], selectionHint: "Choose when the image is clear but needs one concise explanation.", durationFrames: { min: 120, ideal: 165, max: 220 }, textBudget: { body: 150 } }),
];

const capabilityMap = new Map(componentCapabilities.map((capability) => [capability.slug, capability]));

export const getComponentCapability = (slug: string): ComponentCapability | undefined => capabilityMap.get(slug);

export interface ComponentSelectionQuery {
  narrativeRole?: NarrativeRole;
  informationShape?: InformationShape;
  tone?: ComponentTone;
  availableImages?: number;
  needsIconSupport?: boolean;
  providedInputs?: string[];
  maxResults?: number;
}

export interface ComponentRecommendation {
  slug: string;
  name: string;
  score: number;
  reasons: string[];
  missingRequiredInputs: string[];
  capability: ComponentCapability;
}

export const recommendComponents = (query: ComponentSelectionQuery): ComponentRecommendation[] => {
  const availableImages = query.availableImages ?? 0;
  const providedInputs = new Set(query.providedInputs ?? []);
  return componentCapabilities
    .map((capability) => {
      let score = 0;
      const reasons: string[] = [];
      if (query.narrativeRole && capability.narrativeRoles.includes(query.narrativeRole)) { score += 5; reasons.push(`matches ${query.narrativeRole} narrative role`); }
      if (query.informationShape && capability.informationShapes.includes(query.informationShape)) { score += 5; reasons.push(`fits ${query.informationShape} information`); }
      if (query.tone && capability.tones.includes(query.tone)) { score += 2; reasons.push(`supports ${query.tone} tone`); }
      if (query.needsIconSupport && capability.icons.accepts) { score += 1; reasons.push("accepts story-specific icons"); }
      const mediaFits = availableImages >= capability.media.min && availableImages <= capability.media.max;
      if (mediaFits) { score += 3; reasons.push(`fits ${availableImages} available image${availableImages === 1 ? "" : "s"}`); } else if (availableImages < capability.media.min) score -= 8;
      const missingRequiredInputs = capability.inputs.filter((field) => field.required && providedInputs.size > 0 && !providedInputs.has(field.name)).map((field) => field.name);
      score -= missingRequiredInputs.length * 2;
      return { slug: capability.slug, name: capability.name, score, reasons, missingRequiredInputs, capability };
    })
    .sort((a, b) => b.score - a.score || a.slug.localeCompare(b.slug))
    .slice(0, query.maxResults ?? 5);
};

export const getLlmComponentCatalog = (): { version: string; designLanguage: string; components: ComponentCapability[] } => ({
  version: "2.0.0",
  designLanguage: "Broadcast Archive — public-broadcast typography, museum labels, tactile archival media, asymmetric editorial framing, and restrained semantic color.",
  components: componentCapabilities,
});
