/**
 * S23 — Kids Storytelling Video Spike.
 *
 * Takes the scene plan generated by the S23 DeepSeek story+scene stage
 * (spikes/output/s23/02-scene-plan.json) and turns it into a complete
 * short kids storytelling video using:
 *   - The @automation/remotion-templates KIDS namespace components
 *   - Real images sourced from Wikipedia/Wikimedia (fallback: Gemini generation)
 *   - Child-friendly Gemini TTS narration (Algenib voice, warm/energetic delivery)
 *   - Background music mixing via FFmpeg (kids-appropriate levels)
 *   - Remotion CLI rendering to MP4
 *
 * Gated pipeline (each stage persists JSON artifacts to spikes/output/s23-kids/):
 *   1. Load scene plan — read the S23 DeepSeek scene plan from disk
 *   2. Map scenes     — map each scene to a kids component (slug + data)
 *   3. Images         — source bright images (Wikipedia → Gemini fallback)
 *   4. Narration      — Gemini TTS (Algenib) → WAV via FFmpeg
 *   5. Music Sync     — mix narration + background.mp3 (18% music, -16 LUFS)
 *   6. Timing         — compute per-scene frame offsets from narration duration
 *   7. Composition    — generate render.tsx + composition-config.json
 *   8. Render         — Remotion CLI renders the final MP4
 *
 * Cost tracking: every paid call goes through checkBudget → calculateCost →
 * recordCost. Dry-run mode (DRY_RUN=true) uses placeholder images + dummy
 * WAV (zero cost).
 *
 * Usage:
 *   DRY_RUN=true bun run spikes/s23-kids-video.ts
 *   bun run spikes/s23-kids-video.ts
 *   bun run spikes/s23-kids-video.ts --skip-render   # skip the Remotion render
 *   bun run spikes/s23-kids-video.ts --scene-plan <path>  # custom scene plan path
 */

import { readFile } from "node:fs/promises";
import { join } from "node:path";
import { pathToFileURL } from "node:url";
import { loadEnv, spikeDir, writeArtifact, type SpikeResult } from "./lib/spike.ts";
import { isDryRun } from "@automation/contracts";

// S23 story+scene types
import type { ScenePlanItem, ScenePlan } from "./s23-deepseek-story-scene/types.ts";

// Kids video stage modules
import { mapScenesToKidsComponents, assembleFullNarration, type MappedKidsScene } from "./s23-deepseek-story-scene/kids-video/mapping.ts";
import { sourceImages, type ImageStageOutput } from "./s23-deepseek-story-scene/kids-video/images.ts";
import { generateNarration, type TtsStageOutput } from "./s23-deepseek-story-scene/kids-video/tts.ts";
import { mixMusic, type MusicSyncOutput } from "./s23-deepseek-story-scene/kids-video/music.ts";
import { computeSceneTiming, type SceneTimingPlan } from "./s23-deepseek-story-scene/kids-video/timing.ts";
import { generateComposition, type CompositionOutput } from "./s23-deepseek-story-scene/kids-video/composition.ts";
import { renderVideo, type RenderOutput } from "./s23-deepseek-story-scene/kids-video/render.ts";

// === Constants ===

const SPIKE_ID = "s23-kids";
const DEFAULT_SCENE_PLAN_PATH = "spikes/output/s23/02-scene-plan.json";
const VIDEO_TITLE = "The Quiet Witness";
const CHANNEL_NAME = "kidstorytime";

// === Helpers ===

function costSummary(usd: number): string {
  return `$${usd.toFixed(4)}`;
}

function log(stage: string, msg: string): void {
  console.log(`  [${stage}] ${msg}`);
}

// === Stage 1: Load scene plan ===

async function loadScenePlan(path: string): Promise<ScenePlanItem[]> {
  const raw = await readFile(path, "utf-8");
  const parsed = JSON.parse(raw) as ScenePlan;
  if (!parsed.scenes || !Array.isArray(parsed.scenes) || parsed.scenes.length === 0) {
    throw new Error(`Scene plan at ${path} has no scenes`);
  }
  return parsed.scenes as ScenePlanItem[];
}

// === Main run ===

export async function run(): Promise<SpikeResult> {
  await loadEnv();

  const args = process.argv.slice(2);
  const skipRender = args.includes("--skip-render");
  const scenePlanArgIdx = args.indexOf("--scene-plan");
  const scenePlanPath =
    scenePlanArgIdx >= 0 && args[scenePlanArgIdx + 1]
      ? args[scenePlanArgIdx + 1]!
      : DEFAULT_SCENE_PLAN_PATH;

  console.log("═══════════════════════════════════════════════════════════════");
  console.log("  S23 — Kids Storytelling Video Spike");
  console.log(`  Scene plan: ${scenePlanPath}`);
  console.log(`  Video title: "${VIDEO_TITLE}"`);
  console.log(`  Channel: @${CHANNEL_NAME}`);
  console.log(`  Render: ${skipRender ? "SKIPPED (--skip-render)" : "ENABLED"}`);
  console.log(`  Dry-run: ${isDryRun() ? "YES (placeholder images + dummy audio)" : "NO (real API calls)"}`);
  console.log("═══════════════════════════════════════════════════════════════\n");

  const outDir = await spikeDir(SPIKE_ID);
  const apiKey = process.env.GEMINI_API_KEY ?? "";

  let totalCostUsd = 0;
  const stageCosts: Record<string, number> = {};

  // ─── Stage 1: Load scene plan ──────────────────────────────────────────────
  console.log("▸ Stage 1: Load scene plan...\n");
  let scenes: ScenePlanItem[];
  try {
    scenes = await loadScenePlan(scenePlanPath);
  } catch (err) {
    console.error(`\n✗ Failed to load scene plan: ${err}`);
    console.error(`  Run the S23 story+scene spike first: DRY_RUN=true bun run spikes/s23-deepseek-story-scene.ts`);
    return {
      id: SPIKE_ID,
      name: "Kids Storytelling Video",
      goal: "Turn the S23 scene plan into a kids storytelling video.",
      result: "fail",
      measurements: { dryRun: isDryRun(), error: String(err) },
      notes: `Failed to load scene plan from ${scenePlanPath}. Run the S23 story+scene spike first.`,
      artifactPaths: [],
    };
  }
  log("Load", `OK — ${scenes.length} scenes loaded`);
  console.log();

  // ─── Stage 2: Map scenes to kids components ────────────────────────────────
  console.log("▸ Stage 2: Map scenes to kids components...\n");
  const mapped: MappedKidsScene[] = mapScenesToKidsComponents(scenes, VIDEO_TITLE, CHANNEL_NAME);
  await writeArtifact(SPIKE_ID, "02-mapped-scenes.json", JSON.stringify(mapped, null, 2));
  for (const s of mapped) {
    log("Map", `  ${s.order}. ${s.componentSlug} — needsImage=${s.needsImage} (${s.estimatedDurationSeconds}s)`);
  }
  const fullNarration = assembleFullNarration(mapped);
  log("Map", `Full narration: ${fullNarration.length} chars, ~${Math.ceil(fullNarration.length / 15)}s`);
  console.log();

  // ─── Stage 3: Source images ────────────────────────────────────────────────
  console.log("▸ Stage 3: Image sourcing (Wikipedia → Gemini fallback)...\n");
  const imageResult: ImageStageOutput = await sourceImages(mapped, outDir, apiKey);
  totalCostUsd += imageResult.totalCostUsd;
  stageCosts.images = imageResult.totalCostUsd;
  await writeArtifact(SPIKE_ID, "03-images.json", JSON.stringify(imageResult, null, 2));
  const downloaded = imageResult.images.filter((i) => i.source === "downloaded").length;
  const generated = imageResult.images.filter((i) => i.source === "generated").length;
  const placeholder = imageResult.images.filter((i) => i.source === "placeholder").length;
  log("Images", `${imageResult.images.length} images: ${downloaded} downloaded, ${generated} generated, ${placeholder} placeholder — ${costSummary(imageResult.totalCostUsd)}`);
  console.log();

  // ─── Stage 4: Narration (TTS) ──────────────────────────────────────────────
  console.log("▸ Stage 4: Narration (Gemini TTS, child-friendly)...\n");
  const ttsResult: TtsStageOutput = await generateNarration(fullNarration, outDir, apiKey);
  totalCostUsd += ttsResult.costUsd;
  stageCosts.narration = ttsResult.costUsd;
  await writeArtifact(SPIKE_ID, "04-narration.json", JSON.stringify(ttsResult, null, 2));
  log("Narration", `WAV ${ttsResult.durationSec.toFixed(1)}s — ${costSummary(ttsResult.costUsd)}`);
  console.log();

  // ─── Stage 5: Music sync ───────────────────────────────────────────────────
  console.log("▸ Stage 5: Music sync (narration + background music)...\n");
  const musicResult: MusicSyncOutput = await mixMusic(ttsResult.wavPath, ttsResult.durationSec, outDir);
  await writeArtifact(SPIKE_ID, "05-music-sync.json", JSON.stringify(musicResult, null, 2));
  log("MusicSync", `Mixed audio ${musicResult.durationSec.toFixed(1)}s — ${costSummary(musicResult.costUsd)}`);
  console.log();

  // ─── Stage 6: Compute scene timing ─────────────────────────────────────────
  console.log("▸ Stage 6: Compute scene timing...\n");
  const imageMap: Record<number, string> = {};
  for (const img of imageResult.images) {
    imageMap[img.sceneOrder] = img.relativePath;
  }
  const timingPlan: SceneTimingPlan = computeSceneTiming(mapped, ttsResult.durationSec, imageMap);
  await writeArtifact(SPIKE_ID, "06-timing.json", JSON.stringify(timingPlan, null, 2));
  log("Timing", `${timingPlan.scenes.length} scenes, ${timingPlan.totalFrames} frames (${timingPlan.totalSeconds.toFixed(1)}s)`);
  for (const s of timingPlan.scenes) {
    log("Timing", `  ${s.order}. frames ${s.startFrame}-${s.endFrame} (${s.durationSeconds.toFixed(1)}s) — ${s.componentSlug}`);
  }
  console.log();

  // ─── Stage 7: Composition generation ───────────────────────────────────────
  console.log("▸ Stage 7: Remotion composition generation (kids namespace)...\n");
  const composition: CompositionOutput = await generateComposition(timingPlan, imageResult.images, musicResult, outDir);
  totalCostUsd += composition.costUsd;
  stageCosts.composition = composition.costUsd;
  await writeArtifact(SPIKE_ID, "07-composition.json", JSON.stringify({ ...composition, costUsd: composition.costUsd }, null, 2));
  log("Composition", `Entry: ${composition.renderEntryPath}`);
  log("Composition", `Config: ${composition.configPath}`);
  log("Composition", `Public: ${composition.publicDir}`);
  console.log();

  // ─── Stage 8: Render ───────────────────────────────────────────────────────
  let render: RenderOutput | null = null;
  if (!skipRender) {
    console.log("▸ Stage 8: Render (Remotion CLI)...\n");
    try {
      render = await renderVideo(composition, outDir);
      totalCostUsd += render.costUsd;
      stageCosts.render = render.costUsd;
      await writeArtifact(SPIKE_ID, "08-render.json", JSON.stringify(render, null, 2));
      log("Render", `Video: ${render.videoPath} (${render.durationSec.toFixed(1)}s, ${(render.sizeBytes / 1024 / 1024).toFixed(1)} MB)`);
    } catch (err) {
      console.error(`\n✗ Render failed: ${err}`);
      log("Render", "Render step failed — composition artifacts are still available");
    }
  } else {
    log("Render", "SKIPPED (--skip-render)");
  }
  console.log();

  // ─── Summary ───────────────────────────────────────────────────────────────
  console.log("═══════════════════════════════════════════════════════════════");
  console.log("  SPIKE SUMMARY");
  console.log("═══════════════════════════════════════════════════════════════\n");
  console.log(`  Video title: "${VIDEO_TITLE}"`);
  console.log(`  Dry-run:    ${isDryRun() ? "YES" : "NO"}`);
  console.log(`  Scenes:     ${mapped.length}`);
  console.log(`  Images:     ${imageResult.images.length} (${downloaded} downloaded, ${generated} generated, ${placeholder} placeholder)`);
  console.log(`  Narration:  ${ttsResult.durationSec.toFixed(1)}s`);
  console.log(`  Total frames: ${timingPlan.totalFrames} (${timingPlan.totalSeconds.toFixed(1)}s)`);
  console.log(`  Total cost: ${costSummary(totalCostUsd)}`);
  console.log(`\n  Stage costs:`);
  for (const [stage, cost] of Object.entries(stageCosts)) {
    console.log(`    ${stage}: ${costSummary(cost)}`);
  }
  if (render) {
    console.log(`\n  Video: ${render.videoPath}`);
    console.log(`  Size: ${(render.sizeBytes / 1024 / 1024).toFixed(1)} MB`);
  }
  console.log(`\n  Artifacts: ${outDir}`);
  console.log("═══════════════════════════════════════════════════════════════\n");

  const artifactPaths = [
    join(outDir, "02-mapped-scenes.json"),
    join(outDir, "03-images.json"),
    join(outDir, "04-narration.json"),
    join(outDir, "05-music-sync.json"),
    join(outDir, "06-timing.json"),
    join(outDir, "07-composition.json"),
    join(outDir, "composition-config.json"),
    join(outDir, "render.tsx"),
  ];
  if (render) artifactPaths.push(render.videoPath);

  const result: "pass" | "partial" = render ? "pass" : "partial";

  return {
    id: SPIKE_ID,
    name: "Kids Storytelling Video",
    goal: `Turn the S23 DeepSeek scene plan into a kids storytelling video titled "${VIDEO_TITLE}".`,
    result,
    measurements: {
      videoTitle: VIDEO_TITLE,
      dryRun: isDryRun(),
      scenes: mapped.length,
      imagesDownloaded: downloaded,
      imagesGenerated: generated,
      imagesPlaceholder: placeholder,
      narrationDurationSec: ttsResult.durationSec.toFixed(1),
      totalFrames: timingPlan.totalFrames,
      videoDurationSec: render?.durationSec.toFixed(1) ?? "N/A",
      videoSizeMB: render ? (render.sizeBytes / 1024 / 1024).toFixed(1) : "N/A",
      totalCostUsd: totalCostUsd.toFixed(4),
      imagesCostUsd: stageCosts.images?.toFixed(4) ?? "0",
      narrationCostUsd: stageCosts.narration?.toFixed(4) ?? "0",
    },
    notes: render
      ? `Complete kids video generated: ${render.durationSec.toFixed(1)}s, ${(render.sizeBytes / 1024 / 1024).toFixed(1)} MB. ${mapped.length} kids namespace components. ${downloaded} real images downloaded, ${generated} generated.`
      : `Composition artifacts generated but render skipped or failed. Manual render: bun node_modules/@remotion/cli/remotion-cli.js render ${composition.renderEntryPath} ${composition.compositionId} out.mp4 --public-dir=${composition.publicDir}`,
    artifactPaths,
  };
}

// Run if executed directly
if (import.meta.url === pathToFileURL(process.argv[1]!).href) {
  run()
    .then((result) => {
      console.log(`\nResult: ${result.result}`);
      process.exit(0);
    })
    .catch((err) => {
      console.error("Spike failed:", err);
      process.exit(1);
    });
}
