/**
 * Migration 001 — Initial schema (PostgreSQL).
 *
 * Creates all tables for channels, characters, stories, production data,
 * workflow state, and provider usage tracking.
 *
 * Uses TEXT primary keys (UUIDs generated by the application).
 * All tables include created_at timestamps (TIMESTAMPTZ).
 * Channel isolation is via channel_id foreign keys on all data tables.
 *
 * PostgreSQL adaptations from SQLite:
 * - datetime('now') → now(), column type TEXT → TIMESTAMPTZ for timestamps
 * - REAL → DOUBLE PRECISION for floating point
 * - JSON columns stay as TEXT (app code uses JSON.parse/stringify)
 * - Boolean columns stay as INTEGER (app code uses 0/1 pattern)
 * - "order" stays quoted (reserved word in PostgreSQL too)
 */

import type { Migration } from "./index.ts";

export const migration001: Migration = {
  id: 1,
  name: "initial-schema",
  sql: `
-- === Channel and configuration ===

CREATE TABLE IF NOT EXISTS channels (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE,
  niche TEXT NOT NULL,
  locale TEXT NOT NULL DEFAULT 'en-US',
  content_types TEXT NOT NULL DEFAULT '["fictional_story","psychology_concept_story","true_case"]',
  target_duration_seconds INTEGER NOT NULL DEFAULT 45,
  scene_min INTEGER NOT NULL DEFAULT 4,
  scene_max INTEGER NOT NULL DEFAULT 8,
  story_style TEXT NOT NULL DEFAULT '',
  visual_style TEXT NOT NULL DEFAULT '',
  safety_rules TEXT NOT NULL DEFAULT '{}',
  active_character_version_id TEXT,
  image_provider TEXT NOT NULL DEFAULT 'gemini-flash-image',
  tts_provider TEXT NOT NULL DEFAULT 'kokoro',
  tts_voice_id TEXT NOT NULL DEFAULT 'af_heart',
  similarity_policy TEXT NOT NULL DEFAULT '{}',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS channel_versions (
  id TEXT PRIMARY KEY,
  channel_id TEXT NOT NULL REFERENCES channels(id) ON DELETE CASCADE,
  version INTEGER NOT NULL,
  snapshot TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(channel_id, version)
);

CREATE TABLE IF NOT EXISTS channel_provider_settings (
  id TEXT PRIMARY KEY,
  channel_id TEXT NOT NULL REFERENCES channels(id) ON DELETE CASCADE,
  capability TEXT NOT NULL,
  provider TEXT NOT NULL,
  model TEXT NOT NULL,
  config TEXT NOT NULL DEFAULT '{}',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(channel_id, capability)
);

CREATE TABLE IF NOT EXISTS channel_style_profiles (
  id TEXT PRIMARY KEY,
  channel_id TEXT NOT NULL REFERENCES channels(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  realistic_prompt_block TEXT,
  visual_style_block TEXT,
  negative_constraints TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- === Character data ===

CREATE TABLE IF NOT EXISTS characters (
  id TEXT PRIMARY KEY,
  channel_id TEXT NOT NULL REFERENCES channels(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  role TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS character_versions (
  id TEXT PRIMARY KEY,
  character_id TEXT NOT NULL REFERENCES characters(id) ON DELETE CASCADE,
  version INTEGER NOT NULL,
  bible TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'draft' CHECK(status IN ('draft','frozen','archived')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  frozen_at TIMESTAMPTZ,
  UNIQUE(character_id, version)
);

CREATE TABLE IF NOT EXISTS character_references (
  id TEXT PRIMARY KEY,
  character_version_id TEXT NOT NULL REFERENCES character_versions(id) ON DELETE CASCADE,
  role TEXT NOT NULL,
  file_path TEXT NOT NULL,
  checksum TEXT NOT NULL,
  mime_type TEXT NOT NULL,
  width INTEGER NOT NULL,
  height INTEGER NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- === Workflow runs (must exist before story/asset tables that reference it) ===

CREATE TABLE IF NOT EXISTS workflow_runs (
  id TEXT PRIMARY KEY,
  channel_id TEXT NOT NULL REFERENCES channels(id) ON DELETE CASCADE,
  topic TEXT NOT NULL,
  content_type TEXT,
  status TEXT NOT NULL DEFAULT 'pending' CHECK(status IN ('pending','running','paused','completed','failed','cancelled')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  started_at TIMESTAMPTZ,
  completed_at TIMESTAMPTZ
);

-- === Story data ===

CREATE TABLE IF NOT EXISTS story_candidates (
  id TEXT PRIMARY KEY,
  run_id TEXT NOT NULL REFERENCES workflow_runs(id) ON DELETE CASCADE,
  channel_id TEXT NOT NULL REFERENCES channels(id) ON DELETE CASCADE,
  candidate_json TEXT NOT NULL,
  fingerprint TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS stories (
  id TEXT PRIMARY KEY,
  channel_id TEXT NOT NULL REFERENCES channels(id) ON DELETE CASCADE,
  run_id TEXT NOT NULL REFERENCES workflow_runs(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  content_type TEXT NOT NULL,
  canonical_version_id TEXT,
  character_version_id TEXT REFERENCES character_versions(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  approved_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS story_versions (
  id TEXT PRIMARY KEY,
  story_id TEXT NOT NULL REFERENCES stories(id) ON DELETE CASCADE,
  version INTEGER NOT NULL,
  story_json TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(story_id, version)
);

CREATE TABLE IF NOT EXISTS story_sources (
  id TEXT PRIMARY KEY,
  story_id TEXT NOT NULL REFERENCES stories(id) ON DELETE CASCADE,
  source_id TEXT NOT NULL,
  title TEXT NOT NULL,
  url TEXT,
  excerpt TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS story_claims (
  id TEXT PRIMARY KEY,
  story_id TEXT NOT NULL REFERENCES stories(id) ON DELETE CASCADE,
  claim_id TEXT NOT NULL,
  claim TEXT NOT NULL,
  source_ids TEXT NOT NULL,
  confidence TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS story_embeddings (
  id TEXT PRIMARY KEY,
  story_id TEXT NOT NULL REFERENCES stories(id) ON DELETE CASCADE,
  field_name TEXT NOT NULL,
  embedding TEXT NOT NULL,
  model TEXT NOT NULL,
  model_version TEXT NOT NULL,
  dimensions INTEGER NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS similarity_checks (
  id TEXT PRIMARY KEY,
  candidate_id TEXT NOT NULL REFERENCES story_candidates(id) ON DELETE CASCADE,
  existing_story_id TEXT NOT NULL REFERENCES stories(id) ON DELETE CASCADE,
  exact_match INTEGER NOT NULL DEFAULT 0,
  lexical_score DOUBLE PRECISION NOT NULL DEFAULT 0,
  semantic_score DOUBLE PRECISION NOT NULL DEFAULT 0,
  structural_score DOUBLE PRECISION NOT NULL DEFAULT 0,
  adjudication_json TEXT,
  final_classification TEXT NOT NULL DEFAULT 'original',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- === Production data ===

CREATE TABLE IF NOT EXISTS scenes (
  id TEXT PRIMARY KEY,
  story_id TEXT NOT NULL REFERENCES stories(id) ON DELETE CASCADE,
  "order" INTEGER NOT NULL,
  story_purpose TEXT NOT NULL,
  narration_text TEXT NOT NULL,
  visual_event TEXT NOT NULL,
  character_role TEXT NOT NULL,
  pose_and_expression TEXT NOT NULL,
  environment TEXT NOT NULL,
  camera_framing TEXT NOT NULL,
  lighting_and_mood TEXT NOT NULL,
  expected_duration_seconds DOUBLE PRECISION NOT NULL,
  image_requirement TEXT NOT NULL,
  source_claim_ids TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS narration_segments (
  id TEXT PRIMARY KEY,
  scene_id TEXT NOT NULL REFERENCES scenes(id) ON DELETE CASCADE,
  "order" INTEGER NOT NULL,
  text TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS image_prompts (
  id TEXT PRIMARY KEY,
  scene_id TEXT NOT NULL REFERENCES scenes(id) ON DELETE CASCADE,
  compiled_prompt TEXT NOT NULL,
  provider TEXT NOT NULL,
  model TEXT NOT NULL,
  prompt_hash TEXT NOT NULL,
  reference_ids TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS assets (
  id TEXT PRIMARY KEY,
  channel_id TEXT NOT NULL REFERENCES channels(id) ON DELETE CASCADE,
  run_id TEXT REFERENCES workflow_runs(id) ON DELETE CASCADE,
  scene_id TEXT REFERENCES scenes(id) ON DELETE SET NULL,
  type TEXT NOT NULL,
  file_path TEXT NOT NULL,
  mime_type TEXT NOT NULL,
  width INTEGER,
  height INTEGER,
  duration_ms INTEGER,
  checksum TEXT NOT NULL,
  provider TEXT,
  model TEXT,
  remote_request_id TEXT,
  cost_usd DOUBLE PRECISION,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS voiceovers (
  id TEXT PRIMARY KEY,
  run_id TEXT NOT NULL REFERENCES workflow_runs(id) ON DELETE CASCADE,
  story_id TEXT NOT NULL REFERENCES stories(id) ON DELETE CASCADE,
  master_path TEXT NOT NULL,
  duration_ms INTEGER NOT NULL,
  sample_rate INTEGER NOT NULL,
  provider TEXT NOT NULL,
  model TEXT NOT NULL,
  voice_id TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS timings (
  id TEXT PRIMARY KEY,
  scene_id TEXT NOT NULL REFERENCES scenes(id) ON DELETE CASCADE,
  voiceover_id TEXT NOT NULL REFERENCES voiceovers(id) ON DELETE CASCADE,
  narration_start_ms INTEGER NOT NULL,
  narration_end_ms INTEGER NOT NULL,
  recommended_image_start_ms INTEGER NOT NULL,
  recommended_image_end_ms INTEGER NOT NULL,
  audio_segment_file TEXT,
  narration_text TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS captions (
  id TEXT PRIMARY KEY,
  voiceover_id TEXT NOT NULL REFERENCES voiceovers(id) ON DELETE CASCADE,
  format TEXT NOT NULL,
  precision TEXT NOT NULL,
  file_path TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- === Workflow data ===

CREATE TABLE IF NOT EXISTS workflow_steps (
  id TEXT PRIMARY KEY,
  run_id TEXT NOT NULL REFERENCES workflow_runs(id) ON DELETE CASCADE,
  step_type TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending' CHECK(status IN ('pending','running','waiting_approval','completed','failed','skipped')),
  step_data TEXT NOT NULL DEFAULT '{}',
  result_data TEXT,
  provider TEXT,
  model TEXT,
  estimated_cost_usd DOUBLE PRECISION,
  actual_cost_usd DOUBLE PRECISION,
  lease_expires_at TIMESTAMPTZ,
  started_at TIMESTAMPTZ,
  completed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS workflow_step_attempts (
  id TEXT PRIMARY KEY,
  step_id TEXT NOT NULL REFERENCES workflow_steps(id) ON DELETE CASCADE,
  attempt_number INTEGER NOT NULL,
  status TEXT NOT NULL DEFAULT 'running' CHECK(status IN ('running','completed','failed')),
  provider TEXT,
  model TEXT,
  remote_request_id TEXT,
  cost_usd DOUBLE PRECISION,
  error_message TEXT,
  logs TEXT,
  started_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  completed_at TIMESTAMPTZ,
  UNIQUE(step_id, attempt_number)
);

CREATE TABLE IF NOT EXISTS workflow_events (
  id TEXT PRIMARY KEY,
  run_id TEXT NOT NULL REFERENCES workflow_runs(id) ON DELETE CASCADE,
  step_id TEXT REFERENCES workflow_steps(id) ON DELETE CASCADE,
  event_type TEXT NOT NULL,
  payload TEXT NOT NULL DEFAULT '{}',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS approvals (
  id TEXT PRIMARY KEY,
  run_id TEXT NOT NULL REFERENCES workflow_runs(id) ON DELETE CASCADE,
  step_id TEXT NOT NULL REFERENCES workflow_steps(id) ON DELETE CASCADE,
  approval_type TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending' CHECK(status IN ('pending','approved','rejected')),
  reviewer TEXT,
  notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  decided_at TIMESTAMPTZ
);

-- === Provider usage (cost ledger integration) ===

CREATE TABLE IF NOT EXISTS provider_usage (
  id TEXT PRIMARY KEY,
  run_id TEXT REFERENCES workflow_runs(id) ON DELETE SET NULL,
  step_id TEXT,
  channel_id TEXT REFERENCES channels(id) ON DELETE SET NULL,
  capability TEXT NOT NULL,
  provider TEXT NOT NULL,
  model TEXT NOT NULL,
  input_tokens INTEGER NOT NULL DEFAULT 0,
  output_tokens INTEGER NOT NULL DEFAULT 0,
  image_count INTEGER NOT NULL DEFAULT 0,
  image_resolution TEXT,
  grounding_queries INTEGER NOT NULL DEFAULT 0,
  cost_usd DOUBLE PRECISION NOT NULL DEFAULT 0,
  is_free INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- === Indexes ===

CREATE INDEX IF NOT EXISTS idx_channel_versions_channel ON channel_versions(channel_id);
CREATE INDEX IF NOT EXISTS idx_channel_provider_channel ON channel_provider_settings(channel_id);
CREATE INDEX IF NOT EXISTS idx_channel_style_channel ON channel_style_profiles(channel_id);
CREATE INDEX IF NOT EXISTS idx_characters_channel ON characters(channel_id);
CREATE INDEX IF NOT EXISTS idx_character_versions_char ON character_versions(character_id);
CREATE INDEX IF NOT EXISTS idx_character_refs_version ON character_references(character_version_id);
CREATE INDEX IF NOT EXISTS idx_story_candidates_run ON story_candidates(run_id);
CREATE INDEX IF NOT EXISTS idx_story_candidates_channel ON story_candidates(channel_id);
CREATE INDEX IF NOT EXISTS idx_stories_channel ON stories(channel_id);
CREATE INDEX IF NOT EXISTS idx_stories_run ON stories(run_id);
CREATE INDEX IF NOT EXISTS idx_story_versions_story ON story_versions(story_id);
CREATE INDEX IF NOT EXISTS idx_story_sources_story ON story_sources(story_id);
CREATE INDEX IF NOT EXISTS idx_story_claims_story ON story_claims(story_id);
CREATE INDEX IF NOT EXISTS idx_story_embeddings_story ON story_embeddings(story_id);
CREATE INDEX IF NOT EXISTS idx_similarity_candidate ON similarity_checks(candidate_id);
CREATE INDEX IF NOT EXISTS idx_scenes_story ON scenes(story_id);
CREATE INDEX IF NOT EXISTS idx_narration_scene ON narration_segments(scene_id);
CREATE INDEX IF NOT EXISTS idx_image_prompts_scene ON image_prompts(scene_id);
CREATE INDEX IF NOT EXISTS idx_assets_channel ON assets(channel_id);
CREATE INDEX IF NOT EXISTS idx_assets_run ON assets(run_id);
CREATE INDEX IF NOT EXISTS idx_assets_scene ON assets(scene_id);
CREATE INDEX IF NOT EXISTS idx_voiceovers_run ON voiceovers(run_id);
CREATE INDEX IF NOT EXISTS idx_timings_scene ON timings(scene_id);
CREATE INDEX IF NOT EXISTS idx_timings_voiceover ON timings(voiceover_id);
CREATE INDEX IF NOT EXISTS idx_workflow_runs_channel ON workflow_runs(channel_id);
CREATE INDEX IF NOT EXISTS idx_workflow_runs_status ON workflow_runs(status);
CREATE INDEX IF NOT EXISTS idx_workflow_steps_run ON workflow_steps(run_id);
CREATE INDEX IF NOT EXISTS idx_workflow_steps_status ON workflow_steps(status);
CREATE INDEX IF NOT EXISTS idx_workflow_step_attempts_step ON workflow_step_attempts(step_id);
CREATE INDEX IF NOT EXISTS idx_workflow_events_run ON workflow_events(run_id);
CREATE INDEX IF NOT EXISTS idx_approvals_run ON approvals(run_id);
CREATE INDEX IF NOT EXISTS idx_approvals_status ON approvals(status);
CREATE INDEX IF NOT EXISTS idx_provider_usage_run ON provider_usage(run_id);
CREATE INDEX IF NOT EXISTS idx_provider_usage_channel ON provider_usage(channel_id);
CREATE INDEX IF NOT EXISTS idx_provider_usage_provider ON provider_usage(provider);
CREATE INDEX IF NOT EXISTS idx_provider_usage_created ON provider_usage(created_at);
`,
};
